name: Pipeline Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'

permissions:
  contents: read

jobs:
  analise-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        working-directory: ./app
        run: npm ci

      - name: Executar testes e gerar relatório LCOV
        working-directory: ./app
        run: npm run test:coverage 

      - name: Analisar com SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
        with:
          projectBaseDir: app
          args: >
            -Dsonar.projectKey=NathanDoile_Desafio-I---FlowPay
            -Dsonar.organization=nathandoile
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=src
            -Dsonar.exclusions=**/*.test.js,**/*.test.jsx,**/setupTests.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  deploy-firebase:
    needs: analise-sonar
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências e Gerar Build
        working-directory: ./app
        run: |
          npm ci
          npm run build

      - name: Deploy no Firebase Hosting
        working-directory: ./app
        run: |
          npx firebase-tools deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"