name: Pipeline Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'

permissions:
  contents: read

jobs:
  analise-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Analisar com SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
        with:
          projectBaseDir: app
          args: >
            -Dsonar.projectKey=NathanDoile_Desafio-I---FlowPay
            -Dsonar.organization=nathandoile
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=.